# Generated by Django 3.2.4 on 2021-07-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210713_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='deal_of_today',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='on_flash_sale',
            new_name='hot_deal',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='amount_paid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='install_months',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='is_commission_approved',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_price',
        ),
        migrations.AddField(
            model_name='product',
            name='top_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (2, 'Approved'), (1, 'Paid'), (3, 'Remitted(for doc and dev fees)')], default=0),
        ),
        migrations.CreateModel(
            name='Installmental_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=0)),
                ('install_months', models.IntegerField(default=0)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (2, 'Approved'), (4, 'Completed'), (3, 'Disapproved')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.sales')),
            ],
        ),
    ]
