# Generated by Django 3.2.4 on 2021-07-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210713_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_receipt_sent',
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.sales'),
        ),
    ]
