# Generated by Django 3.2.4 on 2021-07-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210713_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
