# Generated by Django 3.2.4 on 2021-07-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_remove_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Verified'), (3, 'Remitted(for doc and dev fees)')], default=0),
        ),
    ]
