# Generated by Django 3.2.4 on 2021-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_bank_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
