# Generated by Django 3.2.4 on 2021-07-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_auto_20210717_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.bankaccount'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
