# Generated by Django 3.2.4 on 2021-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20210717_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
