# Generated by Django 3.2.4 on 2021-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_auto_20210717_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
