# Generated by Django 3.2.4 on 2021-07-18 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_rename_refferal_user_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installmental_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=0)),
                ('is_commission_approved', models.BooleanField(default=False)),
                ('install_limit', models.IntegerField(default=0)),
                ('last_charge', models.DateField(auto_now=True)),
                ('next_charge', models.DateField(blank=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paying'), (4, 'Completed'), (3, 'Disapproved')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paying'), (2, 'Paid'), (3, 'Remitted(for doc and dev fees)')], default=0)),
                ('type', models.CharField(blank=True, choices=[('Outright', 'Outright'), ('Installmental', 'Installmental')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('discount_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.discountvoucher')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='installmental_sales',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.sale'),
        ),
    ]
