# Generated by Django 3.2.4 on 2021-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_auto_20210718_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_quanity',
            new_name='quanity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quanity_left',
        ),
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(blank=True, choices=[('Outright', 'Outright'), ('Installmental', 'Installmental')], default='Outright', max_length=30, null=True),
        ),
    ]
