# Generated by Django 3.2.4 on 2021-07-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_auto_20210719_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmental_sales',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='installmental_sales',
            name='status',
        ),
    ]
