# Generated by Django 3.2.4 on 2021-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_installmental_sales_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmental_sales',
            name='next_charge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
