# Generated by Django 3.2.4 on 2021-07-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_installmental_sales_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcard',
            name='signature',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
