# Generated by Django 3.2.4 on 2021-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_alter_authcard_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcard',
            name='signature',
            field=models.CharField(max_length=30),
        ),
    ]
