# Generated by Django 3.2.4 on 2021-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_auto_20210720_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='wallettranscation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0),
        ),
        migrations.AlterField(
            model_name='wallettranscation',
            name='type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Topup', 'Topup'), ('Withdrawal', 'Withdrawal')], max_length=30, null=True),
        ),
    ]
