# Generated by Django 3.2.4 on 2021-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0038_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='installment_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettranscation',
            name='type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Topup', 'Topup'), ('Commission', 'Commission'), ('Withdrawal', 'Withdrawal')], max_length=30, null=True),
        ),
    ]
